### ISSUE TITLE
Address shifting

### ISSUE THREAD

**Issue by marius-meissner** [lucazulian/gyuvl53l0x#10]
First, thank you for this awesome crate, which usually works great!

I was only a bit surprised about the address shifting:
https://github.com/lucazulian/gyuvl53l0x/blob/9174435cbd4519c347b07dbef44bb69453c8e42b/src/lib.rs#L75

What is the reason for this?
In my case, this was not necessary. Due to the structure of the library, it is also not possible for a user to bypass this, or am I wrong?

If the assumption is true, what do you think about removing the shift and leaving it up to the caller to decide if this is necessary or not?

**Comment by lucazulian** [comment]
Hi @marius-meissner, you are right, as in [this comment](https://github.com/lucazulian/gyuvl53l0x/blob/master/src/lib.rs#L29) sometimes it is not necessary, and unfortunately, it is hardcoded. I will fix it immediately, or a PR is always welcome! Thanks!

**Comment by marius-meissner** [comment]
Wow, that was fast!
Do you know the root cause why it's sometimes necessary? Just out of curiosity or in case I get into the situation myself.

> or a PR is always welcome

I can gladly provide a PR.
How should we handle the existing interface?
1. Just removing the shifting and it is then a breaking change.
2. a second new constructor without shifting

**Comment by lucazulian** [comment]
We can remove the shifting and introduce a breaking change. I thought about adding a new constructor, but it would, in the end, be an extra piece of code that has no reason to be there. Does it make sense to you?
